from python.lib.board_state import BoardState

DEFAULT_ELEVATION_MAP = [
    [0, 0, 1, 1, 2, 2, 2, None],
    [0, 0, 1, 1, 2, 2, 2, 1],
    [0, 0, 1, 1, 2, 2, 2, 1],
    [0, 0, 1, 1, 1, 1, 1, 1],
    [0, 0, 1, 1, 1, 1, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, -1, -1, -1, 0],
    [0, 0, 0, 0, -1, -1, -1, 0],
    [None, None, 0, 0, -1, -1, -1, 0],
    [None, None, 0, 0, -1, -1, -1, 0],
]

# NOTE:
# x = vertical, rows,
# y = horizontal, cols
DEFAULT_ELEVATION_MAP_SHAPE = (8, 10)

DEFAULT_EXPECTED_OUTPUT_GRID_MAP = {
    (0, 0, 0): BoardState.FILLED_TILE,
    (0, 0, 1): BoardState.FILLED_TILE,
    (0, 0, 2): BoardState.FILLED_TILE,
    (0, 0, 3): BoardState.FILLED_TILE,
    (0, 0, 4): BoardState.FILLED_TILE,
    (0, 0, 5): BoardState.FILLED_TILE,
    (0, 0, 6): BoardState.FILLED_TILE,
    (0, 0, 7): BoardState.FILLED_TILE,
    (1, 0, 0): BoardState.FILLED_TILE,
    (1, 0, 1): BoardState.FILLED_TILE,
    (1, 0, 2): BoardState.FILLED_TILE,
    (1, 0, 3): BoardState.FILLED_TILE,
    (1, 0, 4): BoardState.FILLED_TILE,
    (1, 0, 5): BoardState.FILLED_TILE,
    (1, 0, 6): BoardState.FILLED_TILE,
    (1, 0, 7): BoardState.FILLED_TILE,
    (2, 1, 0): BoardState.FILLED_TILE,
    (2, 1, 1): BoardState.FILLED_TILE,
    (2, 1, 2): BoardState.FILLED_TILE,
    (2, 1, 3): BoardState.FILLED_TILE,
    (2, 1, 4): BoardState.FILLED_TILE,
    (2, 0, 5): BoardState.FILLED_TILE,
    (2, 0, 6): BoardState.FILLED_TILE,
    (2, 0, 7): BoardState.FILLED_TILE,
    (3, 1, 0): BoardState.FILLED_TILE,
    (3, 1, 1): BoardState.FILLED_TILE,
    (3, 1, 2): BoardState.FILLED_TILE,
    (3, 1, 3): BoardState.FILLED_TILE,
    (3, 1, 4): BoardState.FILLED_TILE,
    (3, 0, 5): BoardState.FILLED_TILE,
    (3, 0, 6): BoardState.FILLED_TILE,
    (4, 2, 0): BoardState.FILLED_TILE,
    (4, 2, 1): BoardState.FILLED_TILE,
    (4, 2, 2): BoardState.FILLED_TILE,
    (4, 1, 3): BoardState.FILLED_TILE,
    (4, 1, 4): BoardState.FILLED_TILE,
    (4, 0, 5): BoardState.FILLED_TILE,
    (5, 2, 0): BoardState.FILLED_TILE,
    (5, 2, 1): BoardState.FILLED_TILE,
    (5, 2, 2): BoardState.FILLED_TILE,
    (5, 1, 3): BoardState.FILLED_TILE,
    (5, 1, 4): BoardState.FILLED_TILE,
    (6, 2, 0): BoardState.FILLED_TILE,
    (6, 2, 1): BoardState.FILLED_TILE,
    (6, 2, 2): BoardState.FILLED_TILE,
    (6, 1, 3): BoardState.FILLED_TILE,
    (7, 1, 1): BoardState.FILLED_TILE,
    (7, 1, 2): BoardState.FILLED_TILE,
}
