from enum import Enum


class Events(Enum):
    # Register constants
    EVENT_REQUEST_END_TURN = "EVENT_REQUEST_END_TURN"

    # Character/player movement events
    EVENT_REQUEST_PLAYER_MOVE = "EVENT_REQUEST_PLAYER_MOVE"
    EVENT_PLAYER_MOVE_SUCCESS = "EVENT_PLAYER_MOVE_SUCCESS"
    EVENT_PLAYER_MOVE_FAILED = "EVENT_PLAYER_MOVE_FAILED"
    EVENT_CHARACTER_MOVE_SUCCESS = "EVENT_CHARACTER_MOVE_SUCCESS"
    EVENT_CHARACTER_MOVE_FAILED = "EVENT_CHARACTER_MOVE_FAILED"

    # Cursor movement events
    EVENT_REQUEST_CURSOR_MOVE = "EVENT_REQUEST_CURSOR_MOVE"
    EVENT_CURSOR_MOVE_SUCCESS = "EVENT_CURSOR_MOVE_SUCCESS"
    EVENT_CURSOR_MOVE_FAILED = "EVENT_CURSOR_MOVE_FAILED"
    EVENT_CURSOR_SELECT = "EVENT_CURSOR_SELECT"
    EVENT_GAME_STATE_READY = "EVENT_GAME_STATE_READY"